import { NextRequest, NextResponse } from "next/server";
import { authenticateMcp, auditMcp, type McpScope } from "@/lib/mcpAuth";
import { query, queryOne } from "@/server/db/neon";

export const dynamic = "force-dynamic";
const tools = [
  { name: "list_active_candidates", description: "List active TalentOS candidates.", inputSchema: { type: "object", properties: { search: { type: "string" } } } },
  { name: "list_recent_jobs", description: "List active jobs posted within a freshness window.", inputSchema: { type: "object", properties: { days: { type: "number" }, search: { type: "string" }, limit: { type: "number" } } } },
  { name: "get_candidate_base_resumes", description: "List approved base resumes for a candidate.", inputSchema: { type: "object", required: ["candidate_id"], properties: { candidate_id: { type: "string" } } } },
  { name: "list_applications", description: "List applications with canonical application_stage.", inputSchema: { type: "object", properties: { candidate_id: { type: "string" }, application_stage: { type: "string" }, limit: { type: "number" } } } },
  { name: "get_daily_ae_summary", description: "Return daily AE reviewed, applied, interview, and offer counts.", inputSchema: { type: "object", properties: { timezone: { type: "string" } } } },
  { name: "get_ai_pipeline_status", description: "Return queued, running, completed, and failed workflow counts.", inputSchema: { type: "object", properties: { candidate_id: { type: "string" } } } },
  { name: "create_application", description: "Create an idempotent base-resume application in in_ai_pipeline. Does not mark it applied.", inputSchema: { type: "object", required: ["candidate_id","job_id","base_resume_id","idempotency_key"], properties: { candidate_id: { type: "string" }, job_id: { type: "string" }, base_resume_id: { type: "string" }, idempotency_key: { type: "string" }, assigned_to_user_id: { type: "string" }, note: { type: "string" } } } },
] as const;
const scopeFor: Record<string, McpScope> = { list_active_candidates: "mcp:candidates:read", list_recent_jobs: "mcp:jobs:read", get_candidate_base_resumes: "mcp:resumes:read", list_applications: "mcp:applications:read", get_daily_ae_summary: "mcp:analytics:read", get_ai_pipeline_status: "mcp:workflows:read", create_application: "mcp:applications:create" };
const jsonRpc = (id: unknown, result: unknown) => NextResponse.json({ jsonrpc: "2.0", id, result });
const errorRpc = (id: unknown, code: number, message: string) => NextResponse.json({ jsonrpc: "2.0", id, error: { code, message } }, { status: code === -32601 ? 404 : 400 });

export async function GET(req: NextRequest) { const auth = await authenticateMcp(req); if ("error" in auth) return NextResponse.json({ error: auth.error }, { status: auth.status }); return NextResponse.json({ name: "TalentOS MCP", version: "1.0.0", transport: "streamable-http", tools }); }
export async function POST(req: NextRequest) {
  const requestId = req.headers.get("x-request-id") ?? crypto.randomUUID(); const started = Date.now(); let body: any;
  try { body = await req.json(); } catch { return errorRpc(null, -32700, "Invalid JSON"); }
  const id = body?.id ?? null; const method = body?.method;
  if (method === "initialize") { const auth = await authenticateMcp(req); if ("error" in auth) return NextResponse.json({ error: auth.error }, { status: auth.status }); return jsonRpc(id, { protocolVersion: "2025-03-26", capabilities: { tools: {} }, serverInfo: { name: "TalentOS MCP", version: "1.0.0" } }); }
  const tool = method === "tools/call" ? body?.params?.name : null;
  if (method === "tools/list") { const auth = await authenticateMcp(req); if ("error" in auth) return NextResponse.json({ error: auth.error }, { status: auth.status }); return jsonRpc(id, { tools }); }
  if (method !== "tools/call" || !tool || !scopeFor[tool]) return errorRpc(id, -32601, "Unsupported MCP method");
  const auth = await authenticateMcp(req, [scopeFor[tool]]); if ("error" in auth) return NextResponse.json({ error: auth.error }, { status: auth.status });
  const a = body.params.arguments ?? {}; let result: any;
  try {
    if (tool === "list_active_candidates") result = await query(`SELECT id,name,status,target_roles,preferred_locations,work_mode_preference FROM candidates WHERE status='active' AND ($1='' OR name ILIKE '%'||$1||'%') ORDER BY name`, [String(a.search ?? "")]);
    if (tool === "list_recent_jobs") result = await query(`SELECT id,title,company,location,source,posted_at,job_category,category_tags,source_url FROM jobs WHERE is_active=true AND posted_at >= CURRENT_DATE - $1::int AND ($2='' OR title ILIKE '%'||$2||'%' OR company ILIKE '%'||$2||'%') ORDER BY posted_at DESC LIMIT $3`, [Math.min(30,Math.max(0,Number(a.days ?? 7))),String(a.search ?? ""),Math.min(200,Math.max(1,Number(a.limit ?? 50)))]);
    if (tool === "get_candidate_base_resumes") result = await query(`SELECT id,candidate_id,name,target_industry,target_roles,status,updated_at FROM base_resumes WHERE candidate_id=$1 AND status NOT IN ('archived','disabled') ORDER BY updated_at DESC`, [a.candidate_id]);
    if (tool === "list_applications") result = await query(`SELECT a.id,a.candidate_id,a.job_id,a.base_resume_id,a.application_stage,a.resume_generation_status,a.applied_at,a.assigned_to,a.created_at,j.title,j.company,j.posted_at FROM applications a LEFT JOIN jobs j ON j.id=a.job_id WHERE ($1='' OR a.candidate_id=$1::uuid) AND ($2='' OR a.application_stage=$2) ORDER BY a.created_at DESC LIMIT $3`, [String(a.candidate_id ?? ""),String(a.application_stage ?? ""),Math.min(200,Math.max(1,Number(a.limit ?? 50)))]);
    if (tool === "get_daily_ae_summary") result = await query(`SELECT COALESCE(a.ae_applied_by_name,a.ae_reviewed_by_name,'Unassigned') AS owner,COUNT(*) FILTER (WHERE a.ae_applied_at >= CURRENT_DATE)::int applied,COUNT(*) FILTER (WHERE a.ae_reviewed_at >= CURRENT_DATE)::int reviewed,COUNT(*) FILTER (WHERE a.application_stage='interview' AND a.application_stage_changed_at>=CURRENT_DATE)::int interviews,COUNT(*) FILTER (WHERE a.application_stage='offer' AND a.application_stage_changed_at>=CURRENT_DATE)::int offers FROM applications a WHERE a.ae_applied_at>=CURRENT_DATE OR a.ae_reviewed_at>=CURRENT_DATE OR a.application_stage_changed_at>=CURRENT_DATE GROUP BY 1 ORDER BY applied DESC,reviewed DESC`);
    if (tool === "get_ai_pipeline_status") result = await query(`SELECT COALESCE(w.status,'unlinked') status,COUNT(*)::int count FROM applications a LEFT JOIN application_ai_workflows w ON w.id=a.ai_workflow_id WHERE ($1='' OR a.candidate_id=$1::uuid) GROUP BY 1 ORDER BY 1`, [String(a.candidate_id ?? "")]);
    if (tool === "create_application") { const existing = await queryOne<any>(`SELECT id,candidate_id,job_id,application_stage FROM applications WHERE automation_idempotency_key=$1 OR (candidate_id=$2 AND job_id=$3) LIMIT 1`, [a.idempotency_key,a.candidate_id,a.job_id]); if (existing) result = { idempotent: true, application: existing }; else { const row = await queryOne<any>(`INSERT INTO applications(candidate_id,job_id,status,application_stage,base_resume_id,source_type,assigned_to_user_id,priority,review_status,resume_generation_status,next_action,notes,created_by,automation_idempotency_key) VALUES($1,$2,'assigned','in_ai_pipeline',$3,'base_resume',$4,'normal','not_required','queued','AI tailoring in progress',$5,'mcp',$6) RETURNING id,candidate_id,job_id,base_resume_id,application_stage,resume_generation_status`, [a.candidate_id,a.job_id,a.base_resume_id,a.assigned_to_user_id ?? null,a.note ?? 'Created via TalentOS MCP',a.idempotency_key]); result = { idempotent: false, application: row, next_step: "Start the normal application AI workflow dispatcher" }; } }
    await auditMcp({ keyId: auth.keyId, requestId, tool, action: tool === "create_application" ? "write" : "read", scopes: auth.scopes, success: true, durationMs: Date.now()-started, candidateId: a.candidate_id, jobId: a.job_id, applicationId: result?.application?.id });
    return jsonRpc(id, { content: [{ type: "text", text: JSON.stringify(result) }] });
  } catch (error) { await auditMcp({ keyId: auth.keyId, requestId, tool, action: "error", scopes: auth.scopes, success: false, errorCode: "tool_error", durationMs: Date.now()-started }); return errorRpc(id, -32000, error instanceof Error ? error.message : "Tool failed"); }
}
