import { NextRequest, NextResponse } from "next/server";
import { authenticateMcp, auditMcp, type McpScope } from "@/lib/mcpAuth";
import { query, queryOne } from "@/server/db/neon";
import { retryWorkflow, regenerateAiWorkflowForApplication, triggerAiWorkflowForApplication } from "@/server/services/applicationAiWorkflowService";

export const dynamic = "force-dynamic";
const tools = [
  { name: "list_active_candidates", description: "List active TalentOS candidates.", inputSchema: { type: "object", properties: { search: { type: "string" } } } },
  { name: "list_recent_jobs", description: "List active jobs posted within a freshness window.", inputSchema: { type: "object", properties: { days: { type: "number" }, search: { type: "string" }, limit: { type: "number" } } } },
  { name: "get_candidate_base_resumes", description: "List approved base resumes for a candidate.", inputSchema: { type: "object", required: ["candidate_id"], properties: { candidate_id: { type: "string" } } } },
  { name: "list_applications", description: "List applications with canonical application_stage.", inputSchema: { type: "object", properties: { candidate_id: { type: "string" }, application_stage: { type: "string" }, limit: { type: "number" } } } },
  { name: "get_daily_ae_summary", description: "Return daily AE reviewed, applied, interview, and offer counts.", inputSchema: { type: "object", properties: { timezone: { type: "string" } } } },
  { name: "get_ai_pipeline_status", description: "Return queued, running, completed, and failed workflow counts.", inputSchema: { type: "object", properties: { candidate_id: { type: "string" } } } },
  { name: "create_application", description: "Create an idempotent base-resume application in in_ai_pipeline. Does not mark it applied.", inputSchema: { type: "object", required: ["candidate_id","job_id","base_resume_id","idempotency_key"], properties: { candidate_id: { type: "string" }, job_id: { type: "string" }, base_resume_id: { type: "string" }, idempotency_key: { type: "string" }, assigned_to_user_id: { type: "string" }, note: { type: "string" } } } },
  { name: "rank_jobs_for_candidate", description: "Rank fresh unlogged jobs against every approved base resume for a candidate.", inputSchema: { type: "object", required: ["candidate_id"], properties: { candidate_id: { type: "string" }, days: { type: "number" }, limit: { type: "number" } } } },
  { name: "find_duplicate_applications", description: "Find duplicate candidate/job applications and mirrored job postings.", inputSchema: { type: "object", properties: { candidate_id: { type: "string" } } } },
  { name: "find_missing_sharepoint_exports", description: "Find completed/applied applications without a SharePoint resume export.", inputSchema: { type: "object", properties: { candidate_id: { type: "string" }, limit: { type: "number" } } } },
  { name: "change_application_stage", description: "Change canonical application_stage and record actor, source, reason, and timestamp.", inputSchema: { type: "object", required: ["application_id","to_stage","reason","idempotency_key"], properties: { application_id: { type: "string" }, to_stage: { type: "string" }, reason: { type: "string" }, idempotency_key: { type: "string" } } } },
  { name: "retry_application_workflow", description: "Retry a failed AI workflow for an application.", inputSchema: { type: "object", required: ["application_id"], properties: { application_id: { type: "string" } } } },
  { name: "search_candidate_emails", description: "Search stored Gmail communications for a candidate without exposing refresh tokens.", inputSchema: { type: "object", required: ["candidate_id"], properties: { candidate_id: { type: "string" }, search: { type: "string" }, limit: { type: "number" } } } },
  { name: "regenerate_tailored_resume", description: "Regenerate a tailored resume from the application's recorded base resume.", inputSchema: { type: "object", required: ["application_id"], properties: { application_id: { type: "string" } } } },
] as const;
const scopeFor: Record<string, McpScope> = { list_active_candidates: "mcp:candidates:read", list_recent_jobs: "mcp:jobs:read", get_candidate_base_resumes: "mcp:resumes:read", list_applications: "mcp:applications:read", get_daily_ae_summary: "mcp:analytics:read", get_ai_pipeline_status: "mcp:workflows:read", create_application: "mcp:applications:create", rank_jobs_for_candidate: "mcp:matching:read", find_duplicate_applications: "mcp:applications:read", find_missing_sharepoint_exports: "mcp:applications:read", change_application_stage: "mcp:applications:stage", retry_application_workflow: "mcp:workflows:retry", search_candidate_emails: "mcp:emails:read", regenerate_tailored_resume: "mcp:resumes:regenerate" };
const jsonRpc = (id: unknown, result: unknown) => NextResponse.json({ jsonrpc: "2.0", id, result });
// JSON-RPC errors are application-level responses. Keep the HTTP response at
// 200 so MCP clients do not interpret a valid server response as a transport
// failure and incorrectly fall back from Streamable HTTP to SSE.
const errorRpc = (id: unknown, code: number, message: string) => NextResponse.json({ jsonrpc: "2.0", id, error: { code, message } }, { status: 200 });

export async function GET(req: NextRequest) { const auth = await authenticateMcp(req); if ("error" in auth) return NextResponse.json({ error: auth.error }, { status: auth.status }); return NextResponse.json({ name: "TalentOS MCP", version: "1.0.0", transport: "streamable-http", tools }); }
export async function POST(req: NextRequest) {
  const requestId = req.headers.get("x-request-id") ?? crypto.randomUUID(); const started = Date.now(); let body: any;
  try { body = await req.json(); } catch { return errorRpc(null, -32700, "Invalid JSON"); }
  const id = body?.id ?? null; const method = body?.method;
  if (method === "initialize") { const auth = await authenticateMcp(req); if ("error" in auth) return NextResponse.json({ error: auth.error }, { status: auth.status }); return jsonRpc(id, { protocolVersion: "2025-03-26", capabilities: { tools: {} }, serverInfo: { name: "TalentOS MCP", version: "1.0.0" } }); }
  const tool = method === "tools/call" ? body?.params?.name : null;
  if (method === "tools/list") { const auth = await authenticateMcp(req); if ("error" in auth) return NextResponse.json({ error: auth.error }, { status: auth.status }); return jsonRpc(id, { tools }); }
  if (method !== "tools/call" || !tool || !scopeFor[tool]) return errorRpc(id, -32601, "Unsupported MCP method");
  const auth = await authenticateMcp(req, [scopeFor[tool]]); if ("error" in auth) return NextResponse.json({ error: auth.error }, { status: auth.status });
  const a = body.params.arguments ?? {}; let result: any;
  try {
    if (tool === "list_active_candidates") result = await query(`SELECT id,name,status,target_roles,preferred_locations,work_mode_preference FROM candidates WHERE status='active' AND ($1='' OR name ILIKE '%'||$1||'%') ORDER BY name`, [String(a.search ?? "")]);
    if (tool === "list_recent_jobs") result = await query(`SELECT id,title,company,location,source,posted_at,job_category,category_tags,source_url FROM jobs WHERE is_active=true AND posted_at >= CURRENT_DATE - $1::int AND ($2='' OR title ILIKE '%'||$2||'%' OR company ILIKE '%'||$2||'%') ORDER BY posted_at DESC LIMIT $3`, [Math.min(30,Math.max(0,Number(a.days ?? 7))),String(a.search ?? ""),Math.min(200,Math.max(1,Number(a.limit ?? 50)))]);
    if (tool === "get_candidate_base_resumes") result = await query(`SELECT id,candidate_id,name,target_industry,target_roles,status,updated_at FROM base_resumes WHERE candidate_id=$1 AND status NOT IN ('archived','disabled') ORDER BY updated_at DESC`, [a.candidate_id]);
    if (tool === "list_applications") result = await query(`SELECT a.id,a.candidate_id,a.job_id,a.base_resume_id,a.application_stage,a.resume_generation_status,a.applied_at,a.assigned_to,a.created_at,j.title,j.company,j.posted_at FROM applications a LEFT JOIN jobs j ON j.id=a.job_id WHERE ($1='' OR a.candidate_id=$1::uuid) AND ($2='' OR a.application_stage=$2) ORDER BY a.created_at DESC LIMIT $3`, [String(a.candidate_id ?? ""),String(a.application_stage ?? ""),Math.min(200,Math.max(1,Number(a.limit ?? 50)))]);
    if (tool === "get_daily_ae_summary") result = await query(`SELECT COALESCE(a.ae_applied_by_name,a.ae_reviewed_by_name,'Unassigned') AS owner,COUNT(*) FILTER (WHERE a.ae_applied_at >= CURRENT_DATE)::int applied,COUNT(*) FILTER (WHERE a.ae_reviewed_at >= CURRENT_DATE)::int reviewed,COUNT(*) FILTER (WHERE a.application_stage='interview' AND a.application_stage_changed_at>=CURRENT_DATE)::int interviews,COUNT(*) FILTER (WHERE a.application_stage='offer' AND a.application_stage_changed_at>=CURRENT_DATE)::int offers FROM applications a WHERE a.ae_applied_at>=CURRENT_DATE OR a.ae_reviewed_at>=CURRENT_DATE OR a.application_stage_changed_at>=CURRENT_DATE GROUP BY 1 ORDER BY applied DESC,reviewed DESC`);
    if (tool === "get_ai_pipeline_status") result = await query(`SELECT COALESCE(w.status,'unlinked') status,COUNT(*)::int count FROM applications a LEFT JOIN application_ai_workflows w ON w.id=a.ai_workflow_id WHERE ($1='' OR a.candidate_id=$1::uuid) GROUP BY 1 ORDER BY 1`, [String(a.candidate_id ?? "")]);
    if (tool === "rank_jobs_for_candidate") {
      const resumes = await query<any>("SELECT id,name,target_roles,target_industry,content FROM base_resumes WHERE candidate_id=$1 AND status NOT IN ('archived','disabled')", [a.candidate_id]);
      const jobs = await query<any>(`SELECT j.id,j.title,j.company,j.location,j.source,j.posted_at,j.description_text,j.job_category,j.category_tags FROM jobs j WHERE j.is_active=true AND j.posted_at>=CURRENT_DATE-$2::int AND NOT EXISTS(SELECT 1 FROM applications x WHERE x.candidate_id=$1 AND x.job_id=j.id) ORDER BY j.posted_at DESC LIMIT 500`, [a.candidate_id, Math.min(30, Math.max(1, Number(a.days ?? 7)))]) as any[];
      const words=(r:any)=>[r.name,r.target_industry,...(r.target_roles||[]),JSON.stringify(r.content||{})].join(" ").toLowerCase().split(/[^a-z0-9+#./-]+/).filter((x:string)=>x.length>=4);
      result = jobs.map((j:any)=>{let best:any=null;for(const r of resumes){const w=[...new Set(words(r))];const text=[j.title,j.company,j.job_category,(j.category_tags||[]).join(" "),j.description_text].join(" ").toLowerCase();const hits=w.filter(x=>text.includes(x));const titleHits=w.filter(x=>String(j.title).toLowerCase().includes(x));const score=Math.min(100,titleHits.length*8+hits.length*1.5);if(!best||score>best.score)best={base_resume_id:r.id,base_resume_name:r.name,score:Math.round(score),evidence:hits.slice(0,12)};}return {...j,match:best};}).filter((x:any)=>x.match?.score>=20).sort((x:any,y:any)=>y.match.score-x.match.score).slice(0,Math.min(100,Math.max(1,Number(a.limit??30))));
    }
    if (tool === "find_duplicate_applications") result = await query(`SELECT a.candidate_id,c.name,a.job_id,j.title,j.company,COUNT(*)::int duplicate_count,ARRAY_AGG(a.id) application_ids FROM applications a JOIN candidates c ON c.id=a.candidate_id LEFT JOIN jobs j ON j.id=a.job_id WHERE ($1='' OR a.candidate_id=$1::uuid) GROUP BY a.candidate_id,c.name,a.job_id,j.title,j.company HAVING COUNT(*)>1 ORDER BY duplicate_count DESC`, [String(a.candidate_id ?? "")]);
    if (tool === "find_missing_sharepoint_exports") result = await query(`SELECT a.id application_id,a.candidate_id,c.name candidate_name,j.title,j.company,a.application_stage,a.applied_at FROM applications a JOIN candidates c ON c.id=a.candidate_id LEFT JOIN jobs j ON j.id=a.job_id WHERE ($1='' OR a.candidate_id=$1::uuid) AND a.application_stage IN ('applied','screening','interview','offer') AND NOT EXISTS (SELECT 1 FROM application_resume_exports e WHERE e.application_id=a.id AND e.storage_provider='sharepoint' AND e.status='created') ORDER BY a.applied_at DESC NULLS LAST LIMIT $2`, [String(a.candidate_id ?? ""), Math.min(200,Math.max(1,Number(a.limit??100)))]) as any[];
    if (tool === "change_application_stage") {
      const allowed=["in_ai_pipeline","ready_for_review","ready_for_application","applied","screening","interview","offer","rejected","withdrawn","on_hold","closed"]; if(!allowed.includes(String(a.to_stage))) throw new Error("Unsupported application stage");
      const existing=await queryOne<any>("SELECT id,application_stage FROM applications WHERE id=$1",[a.application_id]); if(!existing) throw new Error("Application not found");
      const prior=await queryOne<any>("SELECT id FROM application_stage_history WHERE application_id=$1 AND reason=$2 ORDER BY changed_at DESC LIMIT 1",[a.application_id,a.idempotency_key]); if(prior) result={idempotent:true,application_id:a.application_id,to_stage:a.to_stage}; else {await query(`UPDATE applications SET application_stage=$1,application_stage_changed_at=now(),application_stage_changed_by_name='MCP connector',updated_at=now() WHERE id=$2`,[a.to_stage,a.application_id]);await query(`INSERT INTO application_stage_history(application_id,from_stage,to_stage,changed_at,changed_by_name,reason,source) VALUES($1,$2,$3,now(),'MCP connector',$4,'mcp')`,[a.application_id,existing.application_stage,a.to_stage,`${a.reason} [${a.idempotency_key}]`]);result={idempotent:false,application_id:a.application_id,from_stage:existing.application_stage,to_stage:a.to_stage};}
    }
    if (tool === "retry_application_workflow") { const app=await queryOne<any>("SELECT id,ai_workflow_id FROM applications WHERE id=$1",[a.application_id]); if(!app) throw new Error("Application not found"); await retryWorkflow(app.ai_workflow_id); result={application_id:app.id,retried:true}; }
    if (tool === "search_candidate_emails") result = await query(`SELECT id,candidate_id,subject,snippet,body_text,from_email,to_emails,direction,ai_category,ai_relevant,sent_at,gmail_thread_id FROM email_communications WHERE candidate_id=$1 AND ($2='' OR subject ILIKE '%'||$2||'%' OR snippet ILIKE '%'||$2||'%' OR from_email ILIKE '%'||$2||'%' OR body_text ILIKE '%'||$2||'%') ORDER BY sent_at DESC LIMIT $3`, [a.candidate_id,String(a.search ?? ""),Math.min(100,Math.max(1,Number(a.limit??25)))]) as any[];
    if (tool === "regenerate_tailored_resume") result = await regenerateAiWorkflowForApplication(a.application_id);
    if (tool === "create_application") { const existing = await queryOne<any>(`SELECT id,candidate_id,job_id,application_stage,ai_workflow_id FROM applications WHERE automation_idempotency_key=$1 OR (candidate_id=$2 AND job_id=$3) LIMIT 1`, [a.idempotency_key,a.candidate_id,a.job_id]); if (existing) result = { idempotent: true, application: existing }; else { const row = await queryOne<any>(`INSERT INTO applications(candidate_id,job_id,status,application_stage,base_resume_id,source_type,assigned_to_user_id,priority,review_status,resume_generation_status,next_action,notes,created_by,automation_idempotency_key) VALUES($1,$2,'assigned','in_ai_pipeline',$3,'base_resume',$4,'normal','not_required','queued','AI tailoring in progress',$5,'mcp',$6) RETURNING id,candidate_id,job_id,base_resume_id,application_stage,resume_generation_status`, [a.candidate_id,a.job_id,a.base_resume_id,a.assigned_to_user_id ?? null,a.note ?? 'Created via TalentOS MCP',a.idempotency_key]); const workflow = await triggerAiWorkflowForApplication(row.id, undefined, a.base_resume_id); result = { idempotent: false, application: row, workflow }; } }
    await auditMcp({ keyId: auth.keyId, requestId, tool, action: tool === "create_application" ? "write" : "read", scopes: auth.scopes, success: true, durationMs: Date.now()-started, candidateId: a.candidate_id, jobId: a.job_id, applicationId: result?.application?.id });
    return jsonRpc(id, { content: [{ type: "text", text: JSON.stringify(result) }] });
  } catch (error) { await auditMcp({ keyId: auth.keyId, requestId, tool, action: "error", scopes: auth.scopes, success: false, errorCode: "tool_error", durationMs: Date.now()-started }); return errorRpc(id, -32000, error instanceof Error ? error.message : "Tool failed"); }
}
