"use client";
import { useEffect, useState } from "react";

type Rule = { id:string; sender_email:string|null; sender_domain:string|null; sender_class:string; creates_tasks:boolean; can_change_stage:boolean; notes:string|null };
const classes = ["job_board_alert","no_reply","human_recruiter","hiring_manager","employer_system","personal","unknown"];
export default function GmailSenderRulesPage() {
  const [rules,setRules]=useState<Rule[]>([]); const [form,setForm]=useState<any>({sender_domain:"",sender_email:"",sender_class:"job_board_alert",creates_tasks:false,can_change_stage:false,notes:""}); const [message,setMessage]=useState("");
  async function load(){const r=await fetch("/api/gmail-sender-rules",{cache:"no-store"}); if(r.ok)setRules(await r.json());}
  useEffect(()=>{void load();},[]);
  async function add(){setMessage(""); const r=await fetch("/api/gmail-sender-rules",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)}); const d=await r.json(); if(!r.ok){setMessage(d.error||"Could not save rule");return;} setMessage("Rule saved"); setForm({...form,sender_domain:"",sender_email:"",notes:""}); void load();}
  return <main className="page-shell" style={{maxWidth:1100}}><p className="page-kicker">Communication intelligence</p><h1>Gmail sender rules</h1><p className="muted">Managers and admins can decide which senders create AE work or influence application stages. Stored email is never deleted by these rules.</p>{message&&<p className="notice">{message}</p>}<section className="card" style={{marginTop:20}}><h2>Add rule</h2><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(180px,1fr))",gap:10}}><input placeholder="Domain, e.g. example.com" value={form.sender_domain} onChange={e=>setForm({...form,sender_domain:e.target.value})}/><input placeholder="Exact sender email (optional)" value={form.sender_email} onChange={e=>setForm({...form,sender_email:e.target.value})}/><select value={form.sender_class} onChange={e=>setForm({...form,sender_class:e.target.value})}>{classes.map(x=><option key={x}>{x}</option>)}</select><label><input type="checkbox" checked={form.creates_tasks} onChange={e=>setForm({...form,creates_tasks:e.target.checked})}/> Creates tasks</label><label><input type="checkbox" checked={form.can_change_stage} onChange={e=>setForm({...form,can_change_stage:e.target.checked})}/> Can change stages</label></div><textarea placeholder="Why this rule exists" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})} style={{width:"100%",marginTop:10}}/><button className="btn-primary" onClick={add} style={{marginTop:10}}>Save rule</button></section><section className="card" style={{marginTop:20}}><h2>Active rules ({rules.length})</h2>{rules.map(r=><div key={r.id} style={{borderTop:"1px solid var(--border)",padding:"12px 0"}}><strong>{r.sender_email||r.sender_domain}</strong><span className="badge" style={{marginLeft:8}}>{r.sender_class}</span><p className="muted" style={{marginBottom:0}}>Tasks: {r.creates_tasks?"yes":"no"} · Stage changes: {r.can_change_stage?"yes":"no"}{r.notes?` · ${r.notes}`:""}</p></div>)}</section></main>;
}
