export var JOB_CEO_CONFIG_DEFAULTS = {
  job_ceo_orchestrator: {
    displayName: "Job CEO",
    temperature: 0.2,
    maxOutputTokens: 32768,
    timeoutMs: 60000,
    maxAttempts: 2,
    approvalPolicy: "auto" as const,
    minimumScore: 0,
    outputSchemaVersion: "CeoPlanV1",
  },
  job_ceo_scout: {
    displayName: "Query Scout",
    temperature: 0.1,
    maxOutputTokens: 32768,
    timeoutMs: 30000,
    maxAttempts: 2,
    approvalPolicy: "auto" as const,
    minimumScore: 0,
    outputSchemaVersion: "ScoutTermsV1",
  },
  job_ceo_qa: {
    displayName: "QA Bouncer",
    temperature: 0.2,
    maxOutputTokens: 32768,
    timeoutMs: 30000,
    maxAttempts: 2,
    approvalPolicy: "auto" as const,
    minimumScore: 0,
    outputSchemaVersion: "QaVerdictV1",
  },
  job_ceo_deep_fetch: {
    displayName: "Deep Fetch",
    temperature: 0.3,
    maxOutputTokens: 32768,
    timeoutMs: 60000,
    maxAttempts: 2,
    approvalPolicy: "auto" as const,
    minimumScore: 0,
    outputSchemaVersion: "DeepFetchResultV1",
  },
  job_ceo_matchmaker: {
    displayName: "Matchmaker",
    temperature: 0.2,
    maxOutputTokens: 32768,
    timeoutMs: 60000,
    maxAttempts: 2,
    approvalPolicy: "auto" as const,
    minimumScore: 0,
    outputSchemaVersion: "MatchmakerResultV1",
  },
  job_ceo_enricher: {
    displayName: "Description Enricher",
    temperature: 0.3,
    maxOutputTokens: 32768,
    timeoutMs: 60000,
    maxAttempts: 2,
    approvalPolicy: "auto" as const,
    minimumScore: 0,
    outputSchemaVersion: "DeepFetchResultV1",
  },
} as const;
