"use client";
import { useEffect, useState } from "react";

type KeyRow = { id: string; name: string; key_prefix: string; scopes: string[]; expires_at: string|null; last_used_at: string|null; revoked_at: string|null; created_at: string };
const defaultScopes = ["mcp:candidates:read","mcp:resumes:read","mcp:jobs:read","mcp:matching:read","mcp:applications:read","mcp:analytics:read","mcp:workflows:read"];
export default function McpKeysPage() {
  const [keys,setKeys]=useState<KeyRow[]>([]); const [available,setAvailable]=useState<string[]>([]); const [name,setName]=useState("Codex"); const [scopes,setScopes]=useState(defaultScopes); const [newKey,setNewKey]=useState(""); const [error,setError]=useState("");
  async function load(){const r=await fetch("/api/mcp-keys",{cache:"no-store"});const d=await r.json();if(!r.ok)throw new Error(d.error||"Could not load keys");setKeys(d.keys);setAvailable(d.available_scopes);}
  useEffect(()=>{void load().catch(e=>setError(e.message));},[]);
  async function create(){setError("");const r=await fetch("/api/mcp-keys",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name,scopes})});const d=await r.json();if(!r.ok){setError(d.error);return;}setNewKey(d.key);await load();}
  async function revoke(id:string){if(!confirm("Revoke this MCP key?"))return;await fetch(`/api/mcp-keys/${id}`,{method:"DELETE"});await load();}
  const config=newKey?JSON.stringify({mcpServers:{talentos:{url:"https://talent.skarion.com/api/mcp",headers:{Authorization:`Bearer ${newKey}`}}}},null,2):"";
  return <main className="page-shell" style={{maxWidth:1000}}><div className="page-header"><div><p className="eyebrow">INTEGRATIONS</p><h1>TalentOS MCP keys</h1><p className="muted">Create separate scoped keys for Codex, Claude, Antigravity, and scheduled agents.</p></div></div>{error&&<p className="notice">{error}</p>}<section className="card"><h2>Create connector key</h2><input className="input" value={name} onChange={e=>setName(e.target.value)} placeholder="Client name"/><p className="muted">Read-only is recommended for exploration. Write tools require explicit scopes.</p><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(260px,1fr))",gap:8}}>{available.map(s=><label key={s} style={{display:"flex",gap:8,alignItems:"center"}}><input type="checkbox" checked={scopes.includes(s)} onChange={e=>setScopes(x=>e.target.checked?[...x,s]:x.filter(y=>y!==s))}/>{s}</label>)}</div><button className="btn-primary" style={{marginTop:14}} onClick={()=>void create()}>Generate MCP key</button>{newKey&&<div className="card" style={{marginTop:14}}><strong>Copy this key now. It will not be shown again.</strong><pre style={{whiteSpace:"pre-wrap",overflowWrap:"anywhere"}}>{newKey}</pre><p className="muted">Client configuration</p><pre style={{whiteSpace:"pre-wrap",overflowWrap:"anywhere"}}>{config}</pre></div>}</section><section className="card" style={{marginTop:16}}><h2>Keys</h2>{keys.length===0?<p className="muted">No MCP keys created.</p>:keys.map(k=><div key={k.id} style={{borderTop:"1px solid var(--border)",padding:"12px 0",display:"flex",justifyContent:"space-between",gap:12,flexWrap:"wrap"}}><div><strong>{k.name}</strong><div className="muted">{k.key_prefix} · {k.scopes.length} scopes · last used {k.last_used_at?new Date(k.last_used_at).toLocaleString():"never"}</div></div>{!k.revoked_at&&<button className="btn" onClick={()=>void revoke(k.id)}>Revoke</button>}</div>)}</section></main>;
}
