-- 046_email_triage_and_gmail_sync.sql
-- Phase 2 of the candidate-portal work: Gmail ingestion + AI triage schema.
-- Additive only — new tables and a new automation_id row. Does not touch
-- applications/jobs/resumes or any existing automation's routing.

-- ============================================================================
-- Register the email_triage automation (gemini-2.5-flash-lite — cheap, high
-- volume classification, same tier already used for job_categorization).
-- ============================================================================
INSERT INTO ai_automations (id, label, description, group_label) VALUES
  ('email_triage', 'Email Triage', 'Classifies inbound candidate Gmail messages for relevance, status signal, and reply needs', 'Candidate Portal')
ON CONFLICT (id) DO NOTHING;

INSERT INTO ai_agent_configs (automation_id, display_name, system_prompt, output_schema_version, temperature, max_output_tokens, timeout_ms, max_attempts, approval_policy, minimum_score, is_active)
VALUES ('email_triage', 'Email Triage', ' ', 'EmailTriageV1', 0.1, 1024, 20000, 2, 'auto', 0, true)
ON CONFLICT (automation_id) DO NOTHING;

INSERT INTO ai_automation_routes (automation_id, provider, rank, model_override, is_enabled) VALUES
  ('email_triage', 'google_vertex_proxy', 1, 'gemini-2.5-flash-lite', true),
  ('email_triage', 'google', 2, 'gemini-2.5-flash-lite', true)
ON CONFLICT (automation_id, rank) DO NOTHING;

-- ============================================================================
-- Raw normalized Gmail messages. Separate from candidate_messages (staff-authored
-- log) — this is machine-ingested data with its own write path and retention rules.
-- ============================================================================
CREATE TABLE IF NOT EXISTS email_communications (
  id                      uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  candidate_id            uuid NOT NULL REFERENCES candidates(id) ON DELETE CASCADE,
  integration_account_id  uuid NOT NULL REFERENCES integration_accounts(id) ON DELETE CASCADE,
  gmail_message_id        text NOT NULL,
  gmail_thread_id         text NOT NULL,
  direction               text NOT NULL CHECK (direction IN ('inbound', 'outbound')),
  from_email              text,
  to_emails               text[],
  subject                 text,
  snippet                 text,
  body_text               text,
  sent_at                 timestamptz NOT NULL,
  ingested_at             timestamptz NOT NULL DEFAULT now(),
  ai_relevant             boolean,
  ai_category             text,
  ai_confidence           numeric,
  ai_summary              text,
  ai_matched_application_id uuid REFERENCES applications(id) ON DELETE SET NULL,
  needs_reply             boolean NOT NULL DEFAULT false,
  replied_at              timestamptz,
  triaged_at              timestamptz,
  created_at              timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS email_comm_gmail_msg_idx ON email_communications (gmail_message_id);
CREATE INDEX IF NOT EXISTS email_comm_candidate_idx ON email_communications (candidate_id);
CREATE INDEX IF NOT EXISTS email_comm_thread_idx ON email_communications (gmail_thread_id);
CREATE INDEX IF NOT EXISTS email_comm_needs_reply_idx ON email_communications (needs_reply, replied_at);
CREATE INDEX IF NOT EXISTS email_comm_untriaged_idx ON email_communications (triaged_at) WHERE triaged_at IS NULL;

-- ============================================================================
-- Manager-facing action items generated by triage.
-- ============================================================================
CREATE TABLE IF NOT EXISTS action_items (
  id                      uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  candidate_id            uuid NOT NULL REFERENCES candidates(id) ON DELETE CASCADE,
  application_id          uuid REFERENCES applications(id) ON DELETE SET NULL,
  email_communication_id  uuid REFERENCES email_communications(id) ON DELETE SET NULL,
  type                    text NOT NULL,
  title                   text NOT NULL,
  description             text,
  suggested_action        text,
  priority                text NOT NULL DEFAULT 'normal' CHECK (priority IN ('low', 'normal', 'high', 'urgent')),
  assigned_to_user_id     uuid REFERENCES profiles(user_id) ON DELETE SET NULL,
  status                  text NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'in_progress', 'done', 'dismissed')),
  resolved_at             timestamptz,
  resolved_by_user_id     uuid REFERENCES profiles(user_id) ON DELETE SET NULL,
  created_at              timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS action_items_status_idx ON action_items (status, priority, created_at);
CREATE INDEX IF NOT EXISTS action_items_candidate_idx ON action_items (candidate_id);
CREATE INDEX IF NOT EXISTS action_items_assigned_idx ON action_items (assigned_to_user_id, status);

-- ============================================================================
-- Per-account Gmail sync cursor (incremental history.list), separate column set
-- so this migration never has to touch integration_accounts' existing shape.
-- ============================================================================
ALTER TABLE integration_accounts
  ADD COLUMN IF NOT EXISTS gmail_history_id text,
  ADD COLUMN IF NOT EXISTS sync_error text;
