// Agent constants and configuration defaults.

export const AGENT_CONFIG_DEFAULTS = {
  application_job_lens: {
    displayName: "Job Lens",
    temperature: 0.2,
    maxOutputTokens: 32768,
    timeoutMs: 120_000,
    maxAttempts: 2,
    approvalPolicy: "auto" as const,
    minimumScore: 0,
  },
  application_resume_forge: {
    displayName: "Resume Forge",
    temperature: 0.3,
    maxOutputTokens: 32768,
    timeoutMs: 180_000,
    maxAttempts: 2,
    approvalPolicy: "risk_based" as const,
    minimumScore: 0,
  },
  application_hiring_panel: {
    displayName: "Hiring Panel",
    temperature: 0.1,
    maxOutputTokens: 32768,
    timeoutMs: 120_000,
    maxAttempts: 2,
    approvalPolicy: "auto" as const,
    minimumScore: 6.0,
  },
  application_final_polish: {
    displayName: "Final Polish",
    temperature: 0.2,
    maxOutputTokens: 32768,
    timeoutMs: 180_000,
    maxAttempts: 2,
    approvalPolicy: "auto" as const,
    minimumScore: 0,
  },
  copilot_fill_planner: {
    displayName: "Copilot Fill Planner",
    temperature: 0.1,
    maxOutputTokens: 4096,
    timeoutMs: 45_000,
    maxAttempts: 2,
    approvalPolicy: "auto" as const,
    minimumScore: 0,
  },
  copilot_question_answerer: {
    displayName: "Copilot Question Answerer",
    temperature: 0.4,
    maxOutputTokens: 2048,
    timeoutMs: 20_000,
    maxAttempts: 2,
    approvalPolicy: "auto" as const,
    minimumScore: 0,
  },
  copilot_ceo: {
    displayName: "Copilot CEO",
    temperature: 0.2,
    maxOutputTokens: 4096,
    timeoutMs: 60_000,
    maxAttempts: 1,
    approvalPolicy: "auto" as const,
    minimumScore: 0,
  },
  copilot_form_analyst: {
    displayName: "Copilot Form Analyst",
    temperature: 0.1,
    maxOutputTokens: 1024,
    timeoutMs: 15_000,
    maxAttempts: 2,
    approvalPolicy: "auto" as const,
    minimumScore: 0,
  },
  copilot_compliance: {
    displayName: "Copilot Compliance",
    temperature: 0.0,
    maxOutputTokens: 2048,
    timeoutMs: 15_000,
    maxAttempts: 2,
    approvalPolicy: "auto" as const,
    minimumScore: 0,
  },
  copilot_correction_reviewer: {
    displayName: "Copilot Correction Reviewer",
    temperature: 0.1,
    maxOutputTokens: 1024,
    timeoutMs: 15_000,
    maxAttempts: 1,
    approvalPolicy: "auto" as const,
    minimumScore: 0,
  },
  copilot_cover_letter: {
    displayName: "Copilot Cover Letter",
    temperature: 0.5,
    maxOutputTokens: 4096,
    timeoutMs: 45_000,
    maxAttempts: 2,
    approvalPolicy: "auto" as const,
    minimumScore: 0,
  },
  application_job_hunter: {
    displayName: "Job Hunter",
    temperature: 0.1,
    maxOutputTokens: 8192,
    timeoutMs: 30000,
    maxAttempts: 2,
    approvalPolicy: "auto" as const,
    minimumScore: 0,
  },
} as const;

export const SCHEMA_VERSIONS = {
  jobAnalysis: "JobAnalysisV1",
  resumeDraft: "ResumeDraftV1",
  reviewScore: "ReviewScoreV1",
  finalResume: "FinalResumeV1",
} as const;
